### PR TITLE
chore(usemin): switch to usemin 3.x.x

### PR DESCRIPTION
**Pull request by stephanebachelier**
Also replace grunt-rev by grunt-filerev.
grunt-rev has not been updated in 2 years and usemin should be used with grunt-filerev

### CODE REVIEW

**Comment by stephanebachelier** [comment]
@ArturT by the way your Gruntfile is quite complex. It may help you to split your Gruntfile.

**Comment by ArturT** [comment]
@stephanebachelier Thanks for tips. I use https://github.com/DaftMonk/generator-angular-fullstack to generate project so it seems not up to date tool. I noticed that `Gruntfile` is to complex when Vim save file operation tooks a few seconds :laughing: I will try to do something about it.

**Comment by ArturT** [comment]
I will merge this PR today.

**Comment by ArturT** [comment]
@stephanebachelier It works, thanks for help!

**Comment by stephanebachelier** [comment]
@ArturT glad it helps you!

**Pull request merged**
